"""add backup_config backup_history tables and can_manage_backups permission

Revision ID: 014a5b7e642c
Revises: 533c75b202df
Create Date: 2026-03-16 13:53:58.573816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014a5b7e642c'
down_revision: Union[str, None] = '533c75b202df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_access_token', sa.Text(), nullable=True),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('google_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('google_drive_folder_name', sa.String(length=255), nullable=True),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('auto_backup_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('auto_backup_hour', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('connected_by', sa.Integer(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_config_id'), 'backup_config', ['id'], unique=False)
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('google_drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('uploaded_to_drive', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_history_id'), 'backup_history', ['id'], unique=False)
    op.add_column('user_permissions', sa.Column('can_manage_backups', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'can_manage_backups')
    op.drop_index(op.f('ix_backup_history_id'), table_name='backup_history')
    op.drop_table('backup_history')
    op.drop_index(op.f('ix_backup_config_id'), table_name='backup_config')
    op.drop_table('backup_config')
    # ### end Alembic commands ###
