"""update presenter and segment2

Revision ID: 090ba67dfd08
Revises: c37e5546990c
Create Date: 2024-12-27 18:48:00.479371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090ba67dfd08'
down_revision: Union[str, None] = 'c37e5546990c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presenters', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('presenters', sa.Column('profilePicture', sa.Text(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('presenters', 'profilePicture')
    op.drop_column('presenters', 'biography')
    # ### end Alembic commands ###
