"""add logistics_access_section and logistics_manage_settings columns

Revision ID: 1c2a6c27e51f
Revises: 2895301813ec
Create Date: 2026-04-06 23:21:14.644831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2a6c27e51f'
down_revision: Union[str, None] = '2895301813ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('logistics_access_section', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_manage_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'logistics_manage_settings')
    op.drop_column('user_permissions', 'logistics_access_section')
    # ### end Alembic commands ###
