"""add logistics module tables

Revision ID: 2895301813ec
Revises: d8385e6d3135
Create Date: 2026-04-06 21:08:14.984344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2895301813ec'
down_revision: Union[str, None] = 'd8385e6d3135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Step 1: Tables without circular FK dependencies ---
    op.create_table('logistics_config_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_type', sa.String(length=50), nullable=False, comment='Type de liste: vehicle_segment, vehicle_status, cargo_type, maintenance_type, document_type, etc.'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Code couleur hexadécimal'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment="Nom d'icône Lucide"),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Données supplémentaires extensibles'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_type', 'name', name='uq_logistics_config_type_name')
    )
    op.create_index(op.f('ix_logistics_config_options_id'), 'logistics_config_options', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_config_options_list_type'), 'logistics_config_options', ['list_type'], unique=False)
    op.create_index('ix_logistics_config_type_active', 'logistics_config_options', ['list_type', 'is_active'], unique=False)

    op.create_table('logistics_global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False, comment='Valeur stockée en chaîne, parsée selon value_type'),
    sa.Column('value_type', sa.String(length=20), nullable=False, comment='Type réel: int, bool, string, float'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )

    # --- Step 2: Cyclic tables WITHOUT cross-FK (drivers, teams, vehicles) ---
    # Create them first without the circular foreign keys
    op.create_table('logistics_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('license_types_json', sa.JSON(), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('adr_certificate_expiry', sa.Date(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('photos_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['inventory_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_driver_company_status', 'logistics_drivers', ['company_id', 'status'], unique=False)
    op.create_index('ix_driver_is_archived', 'logistics_drivers', ['is_archived'], unique=False)
    op.create_index('ix_driver_role', 'logistics_drivers', ['role'], unique=False)
    op.create_index(op.f('ix_logistics_drivers_id'), 'logistics_drivers', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_drivers_is_archived'), 'logistics_drivers', ['is_archived'], unique=False)
    op.create_index(op.f('ix_logistics_drivers_user_id'), 'logistics_drivers', ['user_id'], unique=False)

    op.create_table('logistics_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('internal_reference', sa.String(length=20), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('capacity_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('capacity_unit', sa.String(length=10), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('mileage_counter', sa.Integer(), nullable=True),
    sa.Column('current_driver_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('base_site_id', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_cost', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('photos_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_site_id'], ['inventory_sites.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['inventory_companies.id'], ),
    sa.ForeignKeyConstraint(['current_driver_id'], ['logistics_drivers.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['logistics_config_options.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['logistics_config_options.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['logistics_config_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_reference'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_logistics_vehicles_id'), 'logistics_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_vehicles_is_archived'), 'logistics_vehicles', ['is_archived'], unique=False)
    op.create_index(op.f('ix_logistics_vehicles_registration_number'), 'logistics_vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_logistics_vehicles_segment'), 'logistics_vehicles', ['segment'], unique=False)
    op.create_index('ix_vehicle_company_status', 'logistics_vehicles', ['company_id', 'status_id'], unique=False)
    op.create_index('ix_vehicle_is_archived', 'logistics_vehicles', ['is_archived'], unique=False)
    op.create_index('ix_vehicle_segment', 'logistics_vehicles', ['segment'], unique=False)

    op.create_table('logistics_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('preferred_segment', sa.String(length=20), nullable=True),
    sa.Column('default_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dissolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dissolved_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['inventory_companies.id'], ),
    sa.ForeignKeyConstraint(['default_vehicle_id'], ['logistics_vehicles.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['logistics_drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_logistics_teams_id'), 'logistics_teams', ['id'], unique=False)
    op.create_index('ix_team_company_status', 'logistics_teams', ['company_id', 'status'], unique=False)
    op.create_index('ix_team_leader', 'logistics_teams', ['leader_id'], unique=False)

    # --- Step 3: Add deferred circular FK (drivers → vehicles, drivers → teams) ---
    op.create_foreign_key('fk_driver_assigned_vehicle', 'logistics_drivers', 'logistics_vehicles', ['assigned_vehicle_id'], ['id'])
    op.create_foreign_key('fk_driver_team', 'logistics_drivers', 'logistics_teams', ['team_id'], ['id'])
    op.create_table('logistics_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_name', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['logistics_config_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_entity', 'logistics_documents', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_document_expiry', 'logistics_documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_logistics_documents_entity_id'), 'logistics_documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_logistics_documents_id'), 'logistics_documents', ['id'], unique=False)
    op.create_table('logistics_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mileage_at', sa.Integer(), nullable=True),
    sa.Column('next_maintenance_km', sa.Integer(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('performed_by_name', sa.String(length=255), nullable=True),
    sa.Column('performed_by_type', sa.String(length=20), nullable=True),
    sa.Column('labor_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('parts_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('external_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('parts_used_json', sa.JSON(), nullable=True),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_type_id'], ['logistics_config_options.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['logistics_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_maintenance_id'), 'logistics_maintenance', ['id'], unique=False)
    op.create_index('ix_logi_maintenance_category', 'logistics_maintenance', ['category'], unique=False)
    op.create_index('ix_logi_maintenance_status', 'logistics_maintenance', ['status'], unique=False)
    op.create_index('ix_logi_maintenance_vehicle_date', 'logistics_maintenance', ['vehicle_id', 'scheduled_date'], unique=False)
    op.create_table('logistics_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('co_driver_id', sa.Integer(), nullable=True),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_reference', sa.String(length=100), nullable=True),
    sa.Column('departure_location', sa.String(length=255), nullable=False),
    sa.Column('departure_lat', sa.Float(), nullable=True),
    sa.Column('departure_lng', sa.Float(), nullable=True),
    sa.Column('arrival_location', sa.String(length=255), nullable=False),
    sa.Column('arrival_lat', sa.Float(), nullable=True),
    sa.Column('arrival_lng', sa.Float(), nullable=True),
    sa.Column('distance_planned_km', sa.Float(), nullable=True),
    sa.Column('distance_actual_km', sa.Float(), nullable=True),
    sa.Column('mileage_start', sa.Integer(), nullable=True),
    sa.Column('mileage_end', sa.Integer(), nullable=True),
    sa.Column('planned_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('return_empty', sa.Boolean(), nullable=True),
    sa.Column('cargo_type_id', sa.Integer(), nullable=True),
    sa.Column('cargo_description', sa.Text(), nullable=True),
    sa.Column('cargo_loaded_qty', sa.DECIMAL(precision=12, scale=3), nullable=True),
    sa.Column('cargo_unloaded_qty', sa.DECIMAL(precision=12, scale=3), nullable=True),
    sa.Column('cargo_unit', sa.String(length=20), nullable=True),
    sa.Column('cargo_loss_qty', sa.DECIMAL(precision=12, scale=3), nullable=True),
    sa.Column('cargo_loss_reason', sa.Text(), nullable=True),
    sa.Column('wood_species', sa.String(length=100), nullable=True),
    sa.Column('log_count', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('depotage_cert_number', sa.String(length=50), nullable=True),
    sa.Column('tank_calibrated', sa.Boolean(), nullable=True),
    sa.Column('container_count', sa.Integer(), nullable=True),
    sa.Column('fill_rate_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('revenue', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('fuel_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('toll_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('other_costs', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('photos_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_type_id'], ['logistics_config_options.id'], ),
    sa.ForeignKeyConstraint(['co_driver_id'], ['logistics_drivers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['logistics_drivers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['logistics_teams.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['logistics_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_missions_id'), 'logistics_missions', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_missions_planned_date'), 'logistics_missions', ['planned_date'], unique=False)
    op.create_index(op.f('ix_logistics_missions_reference'), 'logistics_missions', ['reference'], unique=True)
    op.create_index(op.f('ix_logistics_missions_segment'), 'logistics_missions', ['segment'], unique=False)
    op.create_index(op.f('ix_logistics_missions_status'), 'logistics_missions', ['status'], unique=False)
    op.create_index('ix_mission_driver', 'logistics_missions', ['driver_id'], unique=False)
    op.create_index('ix_mission_segment', 'logistics_missions', ['segment'], unique=False)
    op.create_index('ix_mission_status', 'logistics_missions', ['status'], unique=False)
    op.create_index('ix_mission_vehicle_date', 'logistics_missions', ['vehicle_id', 'planned_date'], unique=False)
    op.create_table('logistics_tires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('installed_at_km', sa.Integer(), nullable=False),
    sa.Column('current_km', sa.Integer(), nullable=False),
    sa.Column('max_km', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('installed_at', sa.Date(), nullable=False),
    sa.Column('replaced_at', sa.Date(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['logistics_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_tires_id'), 'logistics_tires', ['id'], unique=False)
    op.create_index('ix_tire_status', 'logistics_tires', ['status'], unique=False)
    op.create_index('ix_tire_vehicle_position', 'logistics_tires', ['vehicle_id', 'position'], unique=False)
    op.create_table('logistics_fuel_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('station_name', sa.String(length=255), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('quantity_liters', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('mileage_at', sa.Integer(), nullable=False),
    sa.Column('consumption_l100km', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('is_full_tank', sa.Boolean(), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['logistics_drivers.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['logistics_missions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['logistics_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fuel_mission', 'logistics_fuel_logs', ['mission_id'], unique=False)
    op.create_index('ix_fuel_vehicle_date', 'logistics_fuel_logs', ['vehicle_id', 'date'], unique=False)
    op.create_index(op.f('ix_logistics_fuel_logs_date'), 'logistics_fuel_logs', ['date'], unique=False)
    op.create_index(op.f('ix_logistics_fuel_logs_id'), 'logistics_fuel_logs', ['id'], unique=False)
    op.create_table('logistics_mission_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=20), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wait_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cargo_quantity', sa.DECIMAL(precision=12, scale=3), nullable=True),
    sa.Column('cargo_unit', sa.String(length=20), nullable=True),
    sa.Column('mileage_at', sa.Integer(), nullable=True),
    sa.Column('photos_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['logistics_missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checkpoint_mission', 'logistics_mission_checkpoints', ['mission_id'], unique=False)
    op.create_index(op.f('ix_logistics_mission_checkpoints_id'), 'logistics_mission_checkpoints', ['id'], unique=False)
    op.add_column('user_permissions', sa.Column('logistics_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_view_all_companies', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_vehicles_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_vehicles_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_vehicles_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_vehicles_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_drivers_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_drivers_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_drivers_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_drivers_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_teams_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_teams_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_teams_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_teams_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_missions_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_missions_view_own', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_missions_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_missions_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_missions_submit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_missions_add_photos', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_missions_approve', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_missions_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_fuel_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_fuel_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_fuel_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_fuel_alerts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_maintenance_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_maintenance_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_maintenance_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_maintenance_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_tires_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_tires_manage', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_documents_manage', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_financial_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_kpi_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_reports_export', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_settings_manage', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop deferred circular FK first
    op.drop_constraint('fk_driver_assigned_vehicle', 'logistics_drivers', type_='foreignkey')
    op.drop_constraint('fk_driver_team', 'logistics_drivers', type_='foreignkey')
    op.drop_column('user_permissions', 'logistics_settings_manage')
    op.drop_column('user_permissions', 'logistics_reports_export')
    op.drop_column('user_permissions', 'logistics_kpi_view')
    op.drop_column('user_permissions', 'logistics_financial_view')
    op.drop_column('user_permissions', 'logistics_documents_manage')
    op.drop_column('user_permissions', 'logistics_tires_manage')
    op.drop_column('user_permissions', 'logistics_tires_view')
    op.drop_column('user_permissions', 'logistics_maintenance_delete')
    op.drop_column('user_permissions', 'logistics_maintenance_edit')
    op.drop_column('user_permissions', 'logistics_maintenance_create')
    op.drop_column('user_permissions', 'logistics_maintenance_view')
    op.drop_column('user_permissions', 'logistics_fuel_alerts')
    op.drop_column('user_permissions', 'logistics_fuel_edit')
    op.drop_column('user_permissions', 'logistics_fuel_create')
    op.drop_column('user_permissions', 'logistics_fuel_view')
    op.drop_column('user_permissions', 'logistics_missions_delete')
    op.drop_column('user_permissions', 'logistics_missions_approve')
    op.drop_column('user_permissions', 'logistics_missions_add_photos')
    op.drop_column('user_permissions', 'logistics_missions_submit')
    op.drop_column('user_permissions', 'logistics_missions_edit')
    op.drop_column('user_permissions', 'logistics_missions_create')
    op.drop_column('user_permissions', 'logistics_missions_view_own')
    op.drop_column('user_permissions', 'logistics_missions_view')
    op.drop_column('user_permissions', 'logistics_teams_delete')
    op.drop_column('user_permissions', 'logistics_teams_edit')
    op.drop_column('user_permissions', 'logistics_teams_create')
    op.drop_column('user_permissions', 'logistics_teams_view')
    op.drop_column('user_permissions', 'logistics_drivers_delete')
    op.drop_column('user_permissions', 'logistics_drivers_edit')
    op.drop_column('user_permissions', 'logistics_drivers_create')
    op.drop_column('user_permissions', 'logistics_drivers_view')
    op.drop_column('user_permissions', 'logistics_vehicles_delete')
    op.drop_column('user_permissions', 'logistics_vehicles_edit')
    op.drop_column('user_permissions', 'logistics_vehicles_create')
    op.drop_column('user_permissions', 'logistics_vehicles_view')
    op.drop_column('user_permissions', 'logistics_view_all_companies')
    op.drop_column('user_permissions', 'logistics_view')
    op.drop_index(op.f('ix_logistics_mission_checkpoints_id'), table_name='logistics_mission_checkpoints')
    op.drop_index('ix_checkpoint_mission', table_name='logistics_mission_checkpoints')
    op.drop_table('logistics_mission_checkpoints')
    op.drop_index(op.f('ix_logistics_fuel_logs_id'), table_name='logistics_fuel_logs')
    op.drop_index(op.f('ix_logistics_fuel_logs_date'), table_name='logistics_fuel_logs')
    op.drop_index('ix_fuel_vehicle_date', table_name='logistics_fuel_logs')
    op.drop_index('ix_fuel_mission', table_name='logistics_fuel_logs')
    op.drop_table('logistics_fuel_logs')
    op.drop_index('ix_tire_vehicle_position', table_name='logistics_tires')
    op.drop_index('ix_tire_status', table_name='logistics_tires')
    op.drop_index(op.f('ix_logistics_tires_id'), table_name='logistics_tires')
    op.drop_table('logistics_tires')
    op.drop_index('ix_mission_vehicle_date', table_name='logistics_missions')
    op.drop_index('ix_mission_status', table_name='logistics_missions')
    op.drop_index('ix_mission_segment', table_name='logistics_missions')
    op.drop_index('ix_mission_driver', table_name='logistics_missions')
    op.drop_index(op.f('ix_logistics_missions_status'), table_name='logistics_missions')
    op.drop_index(op.f('ix_logistics_missions_segment'), table_name='logistics_missions')
    op.drop_index(op.f('ix_logistics_missions_reference'), table_name='logistics_missions')
    op.drop_index(op.f('ix_logistics_missions_planned_date'), table_name='logistics_missions')
    op.drop_index(op.f('ix_logistics_missions_id'), table_name='logistics_missions')
    op.drop_table('logistics_missions')
    op.drop_index('ix_logi_maintenance_vehicle_date', table_name='logistics_maintenance')
    op.drop_index('ix_logi_maintenance_status', table_name='logistics_maintenance')
    op.drop_index('ix_logi_maintenance_category', table_name='logistics_maintenance')
    op.drop_index(op.f('ix_logistics_maintenance_id'), table_name='logistics_maintenance')
    op.drop_table('logistics_maintenance')
    op.drop_index(op.f('ix_logistics_documents_id'), table_name='logistics_documents')
    op.drop_index(op.f('ix_logistics_documents_entity_id'), table_name='logistics_documents')
    op.drop_index('ix_document_expiry', table_name='logistics_documents')
    op.drop_index('ix_document_entity', table_name='logistics_documents')
    op.drop_table('logistics_documents')
    op.drop_index('ix_vehicle_segment', table_name='logistics_vehicles')
    op.drop_index('ix_vehicle_is_archived', table_name='logistics_vehicles')
    op.drop_index('ix_vehicle_company_status', table_name='logistics_vehicles')
    op.drop_index(op.f('ix_logistics_vehicles_segment'), table_name='logistics_vehicles')
    op.drop_index(op.f('ix_logistics_vehicles_registration_number'), table_name='logistics_vehicles')
    op.drop_index(op.f('ix_logistics_vehicles_is_archived'), table_name='logistics_vehicles')
    op.drop_index(op.f('ix_logistics_vehicles_id'), table_name='logistics_vehicles')
    op.drop_table('logistics_vehicles')
    op.drop_index('ix_team_leader', table_name='logistics_teams')
    op.drop_index('ix_team_company_status', table_name='logistics_teams')
    op.drop_index(op.f('ix_logistics_teams_id'), table_name='logistics_teams')
    op.drop_table('logistics_teams')
    op.drop_table('logistics_global_settings')
    op.drop_index(op.f('ix_logistics_drivers_user_id'), table_name='logistics_drivers')
    op.drop_index(op.f('ix_logistics_drivers_is_archived'), table_name='logistics_drivers')
    op.drop_index(op.f('ix_logistics_drivers_id'), table_name='logistics_drivers')
    op.drop_index('ix_driver_role', table_name='logistics_drivers')
    op.drop_index('ix_driver_is_archived', table_name='logistics_drivers')
    op.drop_index('ix_driver_company_status', table_name='logistics_drivers')
    op.drop_table('logistics_drivers')
    op.drop_index('ix_logistics_config_type_active', table_name='logistics_config_options')
    op.drop_index(op.f('ix_logistics_config_options_list_type'), table_name='logistics_config_options')
    op.drop_index(op.f('ix_logistics_config_options_id'), table_name='logistics_config_options')
    op.drop_table('logistics_config_options')
    # ### end Alembic commands ###
