"""add social pinned permissions to user_permissions

Revision ID: 3a8d2b50df23
Revises: 7f3a92b1c4d8
Create Date: 2026-03-11 14:11:18.599695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8d2b50df23'
down_revision: Union[str, None] = '7f3a92b1c4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
