"""add is_synced to social_posts

Revision ID: 48c872301416
Revises: 4c2b3fbd69e2
Create Date: 2026-03-06 18:13:05.853142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c872301416'
down_revision: Union[str, None] = '4c2b3fbd69e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_posts', sa.Column('is_synced', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_posts', 'is_synced')
    # ### end Alembic commands ###
