"""add_vehicle_role_compartments_associations_trailer_pannes

Revision ID: 4ad81fd77717
Revises: f94a7c7b88c4
Create Date: 2026-04-29 13:45:00.012563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad81fd77717'
down_revision: Union[str, None] = 'f94a7c7b88c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics_vehicle_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tractor_id', sa.Integer(), nullable=False),
    sa.Column('trailer_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['inventory_companies.id'], ),
    sa.ForeignKeyConstraint(['tractor_id'], ['logistics_vehicles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trailer_id'], ['logistics_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assoc_company_id', 'logistics_vehicle_associations', ['company_id'], unique=False)
    op.create_index('ix_assoc_tractor_id', 'logistics_vehicle_associations', ['tractor_id'], unique=False)
    op.create_index('ix_assoc_trailer_id', 'logistics_vehicle_associations', ['trailer_id'], unique=False)
    op.create_index(op.f('ix_logistics_vehicle_associations_company_id'), 'logistics_vehicle_associations', ['company_id'], unique=False)
    op.create_index(op.f('ix_logistics_vehicle_associations_id'), 'logistics_vehicle_associations', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_vehicle_associations_tractor_id'), 'logistics_vehicle_associations', ['tractor_id'], unique=False)
    op.create_index(op.f('ix_logistics_vehicle_associations_trailer_id'), 'logistics_vehicle_associations', ['trailer_id'], unique=False)
    op.create_table('logistics_vehicle_compartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('compartment_no', sa.Integer(), nullable=False),
    sa.Column('capacity_liters', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['logistics_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'compartment_no', name='uq_compartment_vehicle_no')
    )
    op.create_index('ix_compartment_vehicle_id', 'logistics_vehicle_compartments', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_logistics_vehicle_compartments_id'), 'logistics_vehicle_compartments', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_vehicle_compartments_vehicle_id'), 'logistics_vehicle_compartments', ['vehicle_id'], unique=False)
    op.add_column('fiches_pannes', sa.Column('trailer_id', sa.Integer(), nullable=True))
    op.add_column('fiches_pannes', sa.Column('defective_element', sa.String(length=20), nullable=True))
    op.create_index('ix_fiches_pannes_trailer_id', 'fiches_pannes', ['trailer_id'], unique=False)
    op.create_foreign_key(None, 'fiches_pannes', 'logistics_vehicles', ['trailer_id'], ['id'])
    op.add_column('logistics_vehicles', sa.Column('vehicle_role', sa.String(length=20), nullable=False, server_default='porteur'))
    op.create_index(op.f('ix_logistics_vehicles_vehicle_role'), 'logistics_vehicles', ['vehicle_role'], unique=False)
    op.create_index('ix_vehicle_role', 'logistics_vehicles', ['vehicle_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_role', table_name='logistics_vehicles')
    op.drop_index(op.f('ix_logistics_vehicles_vehicle_role'), table_name='logistics_vehicles')
    op.drop_column('logistics_vehicles', 'vehicle_role')
    op.drop_constraint(None, 'fiches_pannes', type_='foreignkey')
    op.drop_index('ix_fiches_pannes_trailer_id', table_name='fiches_pannes')
    op.drop_column('fiches_pannes', 'defective_element')
    op.drop_column('fiches_pannes', 'trailer_id')
    op.drop_index(op.f('ix_logistics_vehicle_compartments_vehicle_id'), table_name='logistics_vehicle_compartments')
    op.drop_index(op.f('ix_logistics_vehicle_compartments_id'), table_name='logistics_vehicle_compartments')
    op.drop_index('ix_compartment_vehicle_id', table_name='logistics_vehicle_compartments')
    op.drop_table('logistics_vehicle_compartments')
    op.drop_index(op.f('ix_logistics_vehicle_associations_trailer_id'), table_name='logistics_vehicle_associations')
    op.drop_index(op.f('ix_logistics_vehicle_associations_tractor_id'), table_name='logistics_vehicle_associations')
    op.drop_index(op.f('ix_logistics_vehicle_associations_id'), table_name='logistics_vehicle_associations')
    op.drop_index(op.f('ix_logistics_vehicle_associations_company_id'), table_name='logistics_vehicle_associations')
    op.drop_index('ix_assoc_trailer_id', table_name='logistics_vehicle_associations')
    op.drop_index('ix_assoc_tractor_id', table_name='logistics_vehicle_associations')
    op.drop_index('ix_assoc_company_id', table_name='logistics_vehicle_associations')
    op.drop_table('logistics_vehicle_associations')
    # ### end Alembic commands ###
