"""add now_playing_tracks table for RadioDJ

Revision ID: 4c2b3fbd69e2
Revises: cd4d31b1077d
Create Date: 2026-03-03 11:59:13.013456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2b3fbd69e2'
down_revision: Union[str, None] = 'cd4d31b1077d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table('now_playing_tracks'):
        return

    op.create_table('now_playing_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('track_type', sa.String(length=50), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_now_playing_tracks_started_at', 'now_playing_tracks', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_now_playing_tracks_started_at', table_name='now_playing_tracks')
    op.drop_table('now_playing_tracks')
    # ### end Alembic commands ###
