"""add social_page_insights table

Revision ID: 4d507a930cc2
Revises: a9d4371840fb
Create Date: 2026-03-01 22:22:52.168692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d507a930cc2'
down_revision: Union[str, None] = 'a9d4371840fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_page_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('page_impressions_unique', sa.Integer(), nullable=False),
    sa.Column('page_posts_impressions', sa.Integer(), nullable=False),
    sa.Column('page_posts_impressions_unique', sa.Integer(), nullable=False),
    sa.Column('page_posts_impressions_organic', sa.Integer(), nullable=False),
    sa.Column('page_posts_impressions_paid', sa.Integer(), nullable=False),
    sa.Column('page_post_engagements', sa.Integer(), nullable=False),
    sa.Column('page_views_total', sa.Integer(), nullable=False),
    sa.Column('page_follows', sa.Integer(), nullable=False),
    sa.Column('page_daily_follows', sa.Integer(), nullable=False),
    sa.Column('page_daily_unfollows', sa.Integer(), nullable=False),
    sa.Column('reactions_like', sa.Integer(), nullable=False),
    sa.Column('reactions_love', sa.Integer(), nullable=False),
    sa.Column('reactions_wow', sa.Integer(), nullable=False),
    sa.Column('reactions_haha', sa.Integer(), nullable=False),
    sa.Column('reactions_sorry', sa.Integer(), nullable=False),
    sa.Column('reactions_anger', sa.Integer(), nullable=False),
    sa.Column('page_video_views', sa.Integer(), nullable=False),
    sa.Column('page_video_view_time', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_page_insight_account_date')
    )
    op.create_index(op.f('ix_social_page_insights_account_id'), 'social_page_insights', ['account_id'], unique=False)
    op.create_index(op.f('ix_social_page_insights_date'), 'social_page_insights', ['date'], unique=False)
    op.create_index(op.f('ix_social_page_insights_id'), 'social_page_insights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_page_insights_id'), table_name='social_page_insights')
    op.drop_index(op.f('ix_social_page_insights_date'), table_name='social_page_insights')
    op.drop_index(op.f('ix_social_page_insights_account_id'), table_name='social_page_insights')
    op.drop_table('social_page_insights')
    # ### end Alembic commands ###
