"""add fuel_type_raw to logistics_vehicles

Revision ID: 5a3a4cdd1142
Revises: 4ad81fd77717
Create Date: 2026-04-29 16:36:12.680486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3a4cdd1142'
down_revision: Union[str, None] = '4ad81fd77717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistics_vehicles', sa.Column('fuel_type_raw', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistics_vehicles', 'fuel_type_raw')
    # ### end Alembic commands ###
