"""add vehicle_id to fiches_pannes

Revision ID: 5d4f5469c74d
Revises: 693756ab012b
Create Date: 2026-04-28 11:27:11.851495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4f5469c74d'
down_revision: Union[str, None] = '693756ab012b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiches_pannes', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_index('ix_fiches_pannes_vehicle_id', 'fiches_pannes', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'fiches_pannes', 'logistics_vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiches_pannes', type_='foreignkey')
    op.drop_index('ix_fiches_pannes_vehicle_id', table_name='fiches_pannes')
    op.drop_column('fiches_pannes', 'vehicle_id')
    # ### end Alembic commands ###
