"""add_pannes_module_tables

Revision ID: 6172e678e984
Revises: 1c2a6c27e51f
Create Date: 2026-04-27 13:35:09.054305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6172e678e984'
down_revision: Union[str, None] = '1c2a6c27e51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiches_pannes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_fiche', sa.Integer(), nullable=False),
    sa.Column('date_panne', sa.Date(), nullable=False),
    sa.Column('immatriculation', sa.String(length=255), nullable=False),
    sa.Column('numero_moteur', sa.String(length=100), nullable=True),
    sa.Column('societe', sa.String(length=100), nullable=False),
    sa.Column('km_depart', sa.Integer(), nullable=True),
    sa.Column('km_fin', sa.Integer(), nullable=True),
    sa.Column('service_demande', sa.Text(), nullable=True),
    sa.Column('pieces_commandees', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiches_pannes_date_panne'), 'fiches_pannes', ['date_panne'], unique=False)
    op.create_index('ix_fiches_pannes_date_societe', 'fiches_pannes', ['date_panne', 'societe'], unique=False)
    op.create_index(op.f('ix_fiches_pannes_id'), 'fiches_pannes', ['id'], unique=False)
    op.create_index(op.f('ix_fiches_pannes_immatriculation'), 'fiches_pannes', ['immatriculation'], unique=False)
    op.create_index(op.f('ix_fiches_pannes_numero_fiche'), 'fiches_pannes', ['numero_fiche'], unique=True)
    op.create_index(op.f('ix_fiches_pannes_societe'), 'fiches_pannes', ['societe'], unique=False)
    op.create_index(op.f('ix_fiches_pannes_statut'), 'fiches_pannes', ['statut'], unique=False)
    op.create_index('ix_fiches_pannes_statut_societe', 'fiches_pannes', ['statut', 'societe'], unique=False)
    op.create_table('logistics_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_logistics_invitation_email', 'logistics_invitations', ['email'], unique=False)
    op.create_index('ix_logistics_invitation_entity', 'logistics_invitations', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_logistics_invitations_id'), 'logistics_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_invitations_token'), 'logistics_invitations', ['token'], unique=True)
    op.create_table('acteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('societe', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acteurs_actif', 'acteurs', ['actif'], unique=False)
    op.create_index(op.f('ix_acteurs_id'), 'acteurs', ['id'], unique=False)
    op.create_index('ix_acteurs_role', 'acteurs', ['role'], unique=False)
    op.create_index('ix_acteurs_societe', 'acteurs', ['societe'], unique=False)
    op.create_index('ix_acteurs_user_id', 'acteurs', ['user_id'], unique=False)
    op.create_table('logistics_mechanics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['inventory_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_logistics_mechanic_active', 'logistics_mechanics', ['is_active'], unique=False)
    op.create_index('ix_logistics_mechanic_company', 'logistics_mechanics', ['company_id'], unique=False)
    op.create_index(op.f('ix_logistics_mechanics_email'), 'logistics_mechanics', ['email'], unique=False)
    op.create_index(op.f('ix_logistics_mechanics_id'), 'logistics_mechanics', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_mechanics_is_active'), 'logistics_mechanics', ['is_active'], unique=False)
    op.create_index(op.f('ix_logistics_mechanics_user_id'), 'logistics_mechanics', ['user_id'], unique=False)
    op.create_table('fiche_acteur',
    sa.Column('fiche_id', sa.Integer(), nullable=False),
    sa.Column('acteur_id', sa.Integer(), nullable=False),
    sa.Column('role_sur_fiche', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['acteur_id'], ['acteurs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiches_pannes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fiche_id', 'acteur_id')
    )
    op.create_index('ix_fiche_acteur_acteur_id', 'fiche_acteur', ['acteur_id'], unique=False)
    op.create_index('ix_fiche_acteur_fiche_id', 'fiche_acteur', ['fiche_id'], unique=False)
    op.add_column('logistics_maintenance', sa.Column('reference', sa.String(length=20), nullable=True))
    op.add_column('logistics_maintenance', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('logistics_maintenance', sa.Column('mileage_start', sa.Integer(), nullable=True))
    op.add_column('logistics_maintenance', sa.Column('mileage_end', sa.Integer(), nullable=True))
    op.add_column('logistics_maintenance', sa.Column('mechanics_json', sa.JSON(), nullable=True))
    op.add_column('logistics_maintenance', sa.Column('engine_reference', sa.String(length=100), nullable=True))
    op.add_column('logistics_maintenance', sa.Column('reported_by_driver_id', sa.Integer(), nullable=True))
    op.add_column('logistics_maintenance', sa.Column('operations_manager', sa.String(length=255), nullable=True))
    op.create_index('ix_logi_maintenance_priority', 'logistics_maintenance', ['priority'], unique=False)
    op.create_index(op.f('ix_logistics_maintenance_reference'), 'logistics_maintenance', ['reference'], unique=True)
    op.create_foreign_key(None, 'logistics_maintenance', 'logistics_drivers', ['reported_by_driver_id'], ['id'])
    op.add_column('user_permissions', sa.Column('pannes_access_section', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_view_all_companies', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('acteurs_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('acteurs_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('acteurs_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('acteurs_link_account', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'acteurs_link_account')
    op.drop_column('user_permissions', 'acteurs_edit')
    op.drop_column('user_permissions', 'acteurs_create')
    op.drop_column('user_permissions', 'acteurs_view')
    op.drop_column('user_permissions', 'pannes_view_all_companies')
    op.drop_column('user_permissions', 'pannes_delete')
    op.drop_column('user_permissions', 'pannes_edit')
    op.drop_column('user_permissions', 'pannes_create')
    op.drop_column('user_permissions', 'pannes_view')
    op.drop_column('user_permissions', 'pannes_access_section')
    op.drop_constraint(None, 'logistics_maintenance', type_='foreignkey')
    op.drop_index(op.f('ix_logistics_maintenance_reference'), table_name='logistics_maintenance')
    op.drop_index('ix_logi_maintenance_priority', table_name='logistics_maintenance')
    op.drop_column('logistics_maintenance', 'operations_manager')
    op.drop_column('logistics_maintenance', 'reported_by_driver_id')
    op.drop_column('logistics_maintenance', 'engine_reference')
    op.drop_column('logistics_maintenance', 'mechanics_json')
    op.drop_column('logistics_maintenance', 'mileage_end')
    op.drop_column('logistics_maintenance', 'mileage_start')
    op.drop_column('logistics_maintenance', 'priority')
    op.drop_column('logistics_maintenance', 'reference')
    op.drop_index('ix_fiche_acteur_fiche_id', table_name='fiche_acteur')
    op.drop_index('ix_fiche_acteur_acteur_id', table_name='fiche_acteur')
    op.drop_table('fiche_acteur')
    op.drop_index(op.f('ix_logistics_mechanics_user_id'), table_name='logistics_mechanics')
    op.drop_index(op.f('ix_logistics_mechanics_is_active'), table_name='logistics_mechanics')
    op.drop_index(op.f('ix_logistics_mechanics_id'), table_name='logistics_mechanics')
    op.drop_index(op.f('ix_logistics_mechanics_email'), table_name='logistics_mechanics')
    op.drop_index('ix_logistics_mechanic_company', table_name='logistics_mechanics')
    op.drop_index('ix_logistics_mechanic_active', table_name='logistics_mechanics')
    op.drop_table('logistics_mechanics')
    op.drop_index('ix_acteurs_user_id', table_name='acteurs')
    op.drop_index('ix_acteurs_societe', table_name='acteurs')
    op.drop_index('ix_acteurs_role', table_name='acteurs')
    op.drop_index(op.f('ix_acteurs_id'), table_name='acteurs')
    op.drop_index('ix_acteurs_actif', table_name='acteurs')
    op.drop_table('acteurs')
    op.drop_index(op.f('ix_logistics_invitations_token'), table_name='logistics_invitations')
    op.drop_index(op.f('ix_logistics_invitations_id'), table_name='logistics_invitations')
    op.drop_index('ix_logistics_invitation_entity', table_name='logistics_invitations')
    op.drop_index('ix_logistics_invitation_email', table_name='logistics_invitations')
    op.drop_table('logistics_invitations')
    op.drop_index('ix_fiches_pannes_statut_societe', table_name='fiches_pannes')
    op.drop_index(op.f('ix_fiches_pannes_statut'), table_name='fiches_pannes')
    op.drop_index(op.f('ix_fiches_pannes_societe'), table_name='fiches_pannes')
    op.drop_index(op.f('ix_fiches_pannes_numero_fiche'), table_name='fiches_pannes')
    op.drop_index(op.f('ix_fiches_pannes_immatriculation'), table_name='fiches_pannes')
    op.drop_index(op.f('ix_fiches_pannes_id'), table_name='fiches_pannes')
    op.drop_index('ix_fiches_pannes_date_societe', table_name='fiches_pannes')
    op.drop_index(op.f('ix_fiches_pannes_date_panne'), table_name='fiches_pannes')
    op.drop_table('fiches_pannes')
    # ### end Alembic commands ###
