"""rename_pannes_acteurs_columns_add_logistics_prefix

Revision ID: 673dd2272d7a
Revises: 6172e678e984
Create Date: 2026-04-27 16:21:50.736933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673dd2272d7a'
down_revision: Union[str, None] = '6172e678e984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('logistics_pannes_access_section', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_pannes_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_pannes_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_pannes_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_pannes_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_pannes_view_all_companies', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_acteurs_view', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_acteurs_create', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_acteurs_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('logistics_acteurs_link_account', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('user_permissions', 'pannes_access_section')
    op.drop_column('user_permissions', 'pannes_edit')
    op.drop_column('user_permissions', 'pannes_create')
    op.drop_column('user_permissions', 'pannes_view_all_companies')
    op.drop_column('user_permissions', 'acteurs_link_account')
    op.drop_column('user_permissions', 'acteurs_edit')
    op.drop_column('user_permissions', 'pannes_delete')
    op.drop_column('user_permissions', 'acteurs_view')
    op.drop_column('user_permissions', 'pannes_view')
    op.drop_column('user_permissions', 'acteurs_create')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('acteurs_create', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_view', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('acteurs_view', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('acteurs_edit', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('acteurs_link_account', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_view_all_companies', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_create', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_edit', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_permissions', sa.Column('pannes_access_section', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('user_permissions', 'logistics_acteurs_link_account')
    op.drop_column('user_permissions', 'logistics_acteurs_edit')
    op.drop_column('user_permissions', 'logistics_acteurs_create')
    op.drop_column('user_permissions', 'logistics_acteurs_view')
    op.drop_column('user_permissions', 'logistics_pannes_view_all_companies')
    op.drop_column('user_permissions', 'logistics_pannes_delete')
    op.drop_column('user_permissions', 'logistics_pannes_edit')
    op.drop_column('user_permissions', 'logistics_pannes_create')
    op.drop_column('user_permissions', 'logistics_pannes_view')
    op.drop_column('user_permissions', 'logistics_pannes_access_section')
    # ### end Alembic commands ###
