"""add category_id to fiches_pannes

Revision ID: 693756ab012b
Revises: 673dd2272d7a
Create Date: 2026-04-27 17:47:04.444818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693756ab012b'
down_revision: Union[str, None] = '673dd2272d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiches_pannes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index('ix_fiches_pannes_category_id', 'fiches_pannes', ['category_id'], unique=False)
    op.create_foreign_key(None, 'fiches_pannes', 'logistics_config_options', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiches_pannes', type_='foreignkey')
    op.drop_index('ix_fiches_pannes_category_id', table_name='fiches_pannes')
    op.drop_column('fiches_pannes', 'category_id')
    # ### end Alembic commands ###
