"""add ga_properties table

Revision ID: 6e34bb7115f8
Revises: a20fe9263c08
Create Date: 2026-03-25 15:51:58.447835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e34bb7115f8'
down_revision: Union[str, None] = 'a20fe9263c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ga_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ga_properties_id'), 'ga_properties', ['id'], unique=False)
    op.create_index(op.f('ix_ga_properties_property_id'), 'ga_properties', ['property_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ga_properties_property_id'), table_name='ga_properties')
    op.drop_index(op.f('ix_ga_properties_id'), table_name='ga_properties')
    op.drop_table('ga_properties')
    # ### end Alembic commands ###
