"""initial

Revision ID: 89a4d495e633
Revises: 
Create Date: 2026-03-17 15:57:48.728230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89a4d495e633'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_access_token', sa.Text(), nullable=True),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('google_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('google_drive_folder_name', sa.String(length=255), nullable=True),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('auto_backup_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('auto_backup_hour', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('connected_by', sa.Integer(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_config_id'), 'backup_config', ['id'], unique=False)
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('google_drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('uploaded_to_drive', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_history_id'), 'backup_history', ['id'], unique=False)
    op.create_table('emissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emissions_id'), 'emissions', ['id'], unique=False)
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_contact_info'), 'guests', ['contact_info'], unique=False)
    op.create_index(op.f('ix_guests_created_at'), 'guests', ['created_at'], unique=False)
    op.create_index(op.f('ix_guests_name'), 'guests', ['name'], unique=False)
    op.create_index(op.f('ix_guests_updated_at'), 'guests', ['updated_at'], unique=False)
    op.create_table('invite_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_invite_tokens_email'), 'invite_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_invite_tokens_token'), 'invite_tokens', ['token'], unique=False)
    op.create_table('listen_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listen_events_created_at'), 'listen_events', ['created_at'], unique=False)
    op.create_index('ix_listen_events_session_created', 'listen_events', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_listen_events_session_id'), 'listen_events', ['session_id'], unique=False)
    op.create_index('ix_listen_events_type_created', 'listen_events', ['event_type', 'created_at'], unique=False)
    op.create_table('now_playing_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('track_type', sa.String(length=50), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_now_playing_tracks_started_at', 'now_playing_tracks', ['started_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('revoked_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=False)
    op.create_table('role_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('require_2fa', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('profilePicture', sa.Text(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('backup_codes_hash', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_family_name'), 'users', ['family_name'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('archived_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('login_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('presenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('profilePicture', sa.Text(), nullable=True),
    sa.Column('isMainPresenter', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presenters_created_at'), 'presenters', ['created_at'], unique=False)
    op.create_index(op.f('ix_presenters_name'), 'presenters', ['name'], unique=False)
    op.create_index(op.f('ix_presenters_updated_at'), 'presenters', ['updated_at'], unique=False)
    op.create_table('public_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('broadcast_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('emission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['emission_id'], ['emissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_created_by_status_broadcast_date', 'shows', ['created_by', 'status', 'broadcast_date'], unique=False)
    op.create_index('ix_created_by_status_type', 'shows', ['created_by', 'status', 'type'], unique=False)
    op.create_index('ix_show_type_status', 'shows', ['type', 'status'], unique=False)
    op.create_index(op.f('ix_shows_broadcast_date'), 'shows', ['broadcast_date'], unique=False)
    op.create_index(op.f('ix_shows_created_at'), 'shows', ['created_at'], unique=False)
    op.create_index(op.f('ix_shows_created_by'), 'shows', ['created_by'], unique=False)
    op.create_index(op.f('ix_shows_status'), 'shows', ['status'], unique=False)
    op.create_index(op.f('ix_shows_title'), 'shows', ['title'], unique=False)
    op.create_index(op.f('ix_shows_type'), 'shows', ['type'], unique=False)
    op.create_index(op.f('ix_shows_updated_at'), 'shows', ['updated_at'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('connected_by', sa.Integer(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_social_accounts_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_accounts', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_synced', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_id'), 'social_posts', ['id'], unique=False)
    op.create_index(op.f('ix_social_posts_status'), 'social_posts', ['status'], unique=False)
    op.create_table('trusted_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token_hash')
    )
    op.create_index(op.f('ix_trusted_devices_user_id'), 'trusted_devices', ['user_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_acces_showplan_broadcast_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_acces_showplan_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_create_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_edit_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_archive_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_archiveStatusChange_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_destroy_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_changestatus_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_changestatus_owned_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_changestatus_archived_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_setOnline_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_viewAll_showplan', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_acces_users_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_users', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_edit_users', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_desable_users', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete_users', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_manage_roles', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_assign_roles', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_acces_guests_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_guests', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_edit_guests', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete_guests', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_acces_presenters_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_presenters', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_create_presenters', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_edit_presenters', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete_presenters', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_acces_emissions_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_emissions', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_create_emissions', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_edit_emissions', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete_emissions', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_manage_emissions', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_notifications', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_manage_notifications', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_audit_logs', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_login_history', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_manage_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_send_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_view_files', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_upload_files', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_delete_files', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('can_view_tasks', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_create_tasks', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_edit_tasks', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_delete_tasks', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_assign_tasks', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_view_archives', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_destroy_archives', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_restore_archives', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('can_delete_archives', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('quotes_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('quotes_create', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('quotes_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('quotes_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('quotes_publish', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('stream_transcription_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('stream_transcription_create', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('quotes_capture_live', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_view_all_companies', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_view_values', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_create', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_move', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_approve_transfers', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_approve_company_loans', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_maintenance_create', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_maintenance_manage', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_manage_documents', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_manage_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_manage_locations', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_subscriptions_view', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_subscriptions_create', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_subscriptions_edit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_subscriptions_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inventory_subscriptions_manage', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ovh_access_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ovh_view_services', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ovh_view_dashboard', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ovh_view_billing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ovh_view_account', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ovh_manage', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scw_access_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scw_view_instances', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scw_view_dashboard', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scw_view_billing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scw_view_domains', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scw_view_account', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scw_manage', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_access_section', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_view_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_create_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_edit_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_delete_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_publish_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_view_inbox', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_reply_comments', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_delete_comments', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_reply_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_view_stats', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_export_stats', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_manage_accounts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_manage_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_view_articles', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_create_articles', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_edit_articles', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_delete_articles', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_view_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_create_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_edit_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('social_delete_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_enforce_2fa', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_reset_user_2fa', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_manage_backups', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technical_notes', sa.Text(), nullable=True),
    sa.Column('startTime', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segment_title_type', 'segments', ['title', 'type'], unique=False)
    op.create_index(op.f('ix_segments_created_at'), 'segments', ['created_at'], unique=False)
    op.create_index(op.f('ix_segments_title'), 'segments', ['title'], unique=False)
    op.create_index(op.f('ix_segments_type'), 'segments', ['type'], unique=False)
    op.create_index(op.f('ix_segments_updated_at'), 'segments', ['updated_at'], unique=False)
    op.create_table('show_presenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('presenter_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['presenter_id'], ['presenters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_presenters_show_id'), 'show_presenters', ['show_id'], unique=False)
    op.create_table('social_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_comment_id', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('post_content', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_avatar', sa.Text(), nullable=True),
    sa.Column('author_platform_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['social_comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_comment_id')
    )
    op.create_index(op.f('ix_social_comments_id'), 'social_comments', ['id'], unique=False)
    op.create_index(op.f('ix_social_comments_platform'), 'social_comments', ['platform'], unique=False)
    op.create_table('social_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('participant_name', sa.String(length=255), nullable=False),
    sa.Column('participant_avatar', sa.Text(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_conversations_id'), 'social_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_social_conversations_platform'), 'social_conversations', ['platform'], unique=False)
    op.create_table('social_page_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('page_impressions_unique', sa.Integer(), nullable=False),
    sa.Column('page_posts_impressions', sa.Integer(), nullable=False),
    sa.Column('page_posts_impressions_unique', sa.Integer(), nullable=False),
    sa.Column('page_posts_impressions_organic', sa.Integer(), nullable=False),
    sa.Column('page_posts_impressions_paid', sa.Integer(), nullable=False),
    sa.Column('page_post_engagements', sa.Integer(), nullable=False),
    sa.Column('page_views_total', sa.Integer(), nullable=False),
    sa.Column('page_follows', sa.Integer(), nullable=False),
    sa.Column('page_daily_follows', sa.Integer(), nullable=False),
    sa.Column('page_daily_unfollows', sa.Integer(), nullable=False),
    sa.Column('reactions_like', sa.Integer(), nullable=False),
    sa.Column('reactions_love', sa.Integer(), nullable=False),
    sa.Column('reactions_wow', sa.Integer(), nullable=False),
    sa.Column('reactions_haha', sa.Integer(), nullable=False),
    sa.Column('reactions_sorry', sa.Integer(), nullable=False),
    sa.Column('reactions_anger', sa.Integer(), nullable=False),
    sa.Column('page_video_views', sa.Integer(), nullable=False),
    sa.Column('page_video_view_time', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_page_insight_account_date')
    )
    op.create_index(op.f('ix_social_page_insights_account_id'), 'social_page_insights', ['account_id'], unique=False)
    op.create_index(op.f('ix_social_page_insights_date'), 'social_page_insights', ['date'], unique=False)
    op.create_index(op.f('ix_social_page_insights_id'), 'social_page_insights', ['id'], unique=False)
    op.create_table('social_post_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('platform_post_url', sa.Text(), nullable=True),
    sa.Column('platform_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_post_results_id'), 'social_post_results', ['id'], unique=False)
    op.create_table('segment_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('platform_message_id', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('sender_avatar', sa.Text(), nullable=True),
    sa.Column('sender_platform_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['social_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_message_id')
    )
    op.create_index(op.f('ix_social_messages_id'), 'social_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_messages_id'), table_name='social_messages')
    op.drop_table('social_messages')
    op.drop_table('segment_guests')
    op.drop_index(op.f('ix_social_post_results_id'), table_name='social_post_results')
    op.drop_table('social_post_results')
    op.drop_index(op.f('ix_social_page_insights_id'), table_name='social_page_insights')
    op.drop_index(op.f('ix_social_page_insights_date'), table_name='social_page_insights')
    op.drop_index(op.f('ix_social_page_insights_account_id'), table_name='social_page_insights')
    op.drop_table('social_page_insights')
    op.drop_index(op.f('ix_social_conversations_platform'), table_name='social_conversations')
    op.drop_index(op.f('ix_social_conversations_id'), table_name='social_conversations')
    op.drop_table('social_conversations')
    op.drop_index(op.f('ix_social_comments_platform'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_id'), table_name='social_comments')
    op.drop_table('social_comments')
    op.drop_index(op.f('ix_show_presenters_show_id'), table_name='show_presenters')
    op.drop_table('show_presenters')
    op.drop_index(op.f('ix_segments_updated_at'), table_name='segments')
    op.drop_index(op.f('ix_segments_type'), table_name='segments')
    op.drop_index(op.f('ix_segments_title'), table_name='segments')
    op.drop_index(op.f('ix_segments_created_at'), table_name='segments')
    op.drop_index('ix_segment_title_type', table_name='segments')
    op.drop_table('segments')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_trusted_devices_user_id'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    op.drop_index(op.f('ix_social_posts_status'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_social_accounts_platform'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_shows_updated_at'), table_name='shows')
    op.drop_index(op.f('ix_shows_type'), table_name='shows')
    op.drop_index(op.f('ix_shows_title'), table_name='shows')
    op.drop_index(op.f('ix_shows_status'), table_name='shows')
    op.drop_index(op.f('ix_shows_created_by'), table_name='shows')
    op.drop_index(op.f('ix_shows_created_at'), table_name='shows')
    op.drop_index(op.f('ix_shows_broadcast_date'), table_name='shows')
    op.drop_index('ix_show_type_status', table_name='shows')
    op.drop_index('ix_created_by_status_type', table_name='shows')
    op.drop_index('ix_created_by_status_broadcast_date', table_name='shows')
    op.drop_table('shows')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_table('public_alerts')
    op.drop_index(op.f('ix_presenters_updated_at'), table_name='presenters')
    op.drop_index(op.f('ix_presenters_name'), table_name='presenters')
    op.drop_index(op.f('ix_presenters_created_at'), table_name='presenters')
    op.drop_table('presenters')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('notifications')
    op.drop_table('login_history')
    op.drop_table('audit_logs')
    op.drop_table('archived_audit_logs')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_family_name'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('role_templates')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_table('permissions')
    op.drop_index('ix_now_playing_tracks_started_at', table_name='now_playing_tracks')
    op.drop_table('now_playing_tracks')
    op.drop_index('ix_listen_events_type_created', table_name='listen_events')
    op.drop_index(op.f('ix_listen_events_session_id'), table_name='listen_events')
    op.drop_index('ix_listen_events_session_created', table_name='listen_events')
    op.drop_index(op.f('ix_listen_events_created_at'), table_name='listen_events')
    op.drop_table('listen_events')
    op.drop_index(op.f('ix_invite_tokens_token'), table_name='invite_tokens')
    op.drop_index(op.f('ix_invite_tokens_email'), table_name='invite_tokens')
    op.drop_table('invite_tokens')
    op.drop_index(op.f('ix_guests_updated_at'), table_name='guests')
    op.drop_index(op.f('ix_guests_name'), table_name='guests')
    op.drop_index(op.f('ix_guests_created_at'), table_name='guests')
    op.drop_index(op.f('ix_guests_contact_info'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_emissions_id'), table_name='emissions')
    op.drop_table('emissions')
    op.drop_index(op.f('ix_backup_history_id'), table_name='backup_history')
    op.drop_table('backup_history')
    op.drop_index(op.f('ix_backup_config_id'), table_name='backup_config')
    op.drop_table('backup_config')
    # ### end Alembic commands ###
