"""add_2fa_fields

Revision ID: 9f728a09e151
Revises: b2e4a7f39c15
Create Date: 2026-03-13 13:56:34.131798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f728a09e151'
down_revision: Union[str, None] = 'b2e4a7f39c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('can_enforce_2fa', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('can_reset_user_2fa', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('totp_secret_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('backup_codes_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'backup_codes_hash')
    op.drop_column('users', 'totp_secret_encrypted')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('user_permissions', 'can_reset_user_2fa')
    op.drop_column('user_permissions', 'can_enforce_2fa')
    # ### end Alembic commands ###
