"""add inventory module tables

Revision ID: a20fe9263c08
Revises: 89a4d495e633
Create Date: 2026-03-23 14:03:32.311614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20fe9263c08'
down_revision: Union[str, None] = '89a4d495e633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('can_share_equipment', sa.Boolean(), nullable=True),
    sa.Column('can_borrow_equipment', sa.Boolean(), nullable=True),
    sa.Column('requires_approval_to_lend', sa.Boolean(), nullable=True),
    sa.Column('requires_approval_to_borrow', sa.Boolean(), nullable=True),
    sa.Column('parent_company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_company_id'], ['inventory_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_inventory_companies_id'), 'inventory_companies', ['id'], unique=False)
    op.create_table('inventory_config_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_type', sa.String(length=50), nullable=False, comment='Type de liste: category, equipment_status, movement_type, mission_type, condition_state, document_type, service_category'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Code couleur hexadecimal'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment="Nom d'icone Lucide"),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Donnees supplementaires extensibles'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_type', 'name', name='uq_config_option_type_name')
    )
    op.create_index('ix_config_option_type_active', 'inventory_config_options', ['list_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_inventory_config_options_id'), 'inventory_config_options', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_config_options_list_type'), 'inventory_config_options', ['list_type'], unique=False)
    op.create_table('inventory_global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False, comment='Valeur stockee en chaine, parsee selon value_type'),
    sa.Column('value_type', sa.String(length=20), nullable=False, comment='Type reel: int, bool, string, float'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('inventory_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_city', sa.String(length=255), nullable=True),
    sa.Column('address_postal_code', sa.String(length=20), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('manager_user_id', sa.Integer(), nullable=True),
    sa.Column('manager_user_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['inventory_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_site_company_code')
    )
    op.create_index(op.f('ix_inventory_sites_id'), 'inventory_sites', ['id'], unique=False)
    op.create_table('inventory_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('provider_website', sa.Text(), nullable=True),
    sa.Column('provider_contact_email', sa.String(length=255), nullable=True),
    sa.Column('provider_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('provider_account_number', sa.String(length=255), nullable=True),
    sa.Column('cost_amount', sa.Float(), nullable=False),
    sa.Column('cost_currency', sa.String(length=10), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('renewal_type', sa.String(length=20), nullable=False),
    sa.Column('auto_renew_period_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('login_url', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_config_options.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['inventory_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_subscriptions_id'), 'inventory_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_subscriptions_is_archived'), 'inventory_subscriptions', ['is_archived'], unique=False)
    op.create_index('ix_subscription_company', 'inventory_subscriptions', ['company_id'], unique=False)
    op.create_index('ix_subscription_end_date', 'inventory_subscriptions', ['end_date'], unique=False)
    op.create_index('ix_subscription_is_archived', 'inventory_subscriptions', ['is_archived'], unique=False)
    op.create_index('ix_subscription_status', 'inventory_subscriptions', ['status'], unique=False)
    op.create_table('inventory_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['inventory_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_rooms_id'), 'inventory_rooms', ['id'], unique=False)
    op.create_table('inventory_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('specific_location', sa.String(length=255), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_user_name', sa.String(length=255), nullable=True),
    sa.Column('assigned_user_email', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('expected_return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignment_notes', sa.Text(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_type', sa.String(length=50), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('warranty_start_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('warranty_provider', sa.String(length=255), nullable=True),
    sa.Column('warranty_contract_number', sa.String(length=255), nullable=True),
    sa.Column('warranty_notes', sa.Text(), nullable=True),
    sa.Column('config_settings_json', sa.JSON(), nullable=True),
    sa.Column('config_notes', sa.Text(), nullable=True),
    sa.Column('last_configured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_configured_by', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('software_version', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('manual_url', sa.Text(), nullable=True),
    sa.Column('photos_json', sa.JSON(), nullable=True),
    sa.Column('specifications_json', sa.JSON(), nullable=True),
    sa.Column('is_consumable', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_config_options.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['inventory_companies.id'], ),
    sa.ForeignKeyConstraint(['condition_id'], ['inventory_config_options.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['inventory_rooms.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['inventory_sites.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['inventory_config_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipment_category', 'inventory_equipment', ['category_id'], unique=False)
    op.create_index('ix_equipment_company_status', 'inventory_equipment', ['company_id', 'status_id'], unique=False)
    op.create_index('ix_equipment_is_archived', 'inventory_equipment', ['is_archived'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_barcode'), 'inventory_equipment', ['barcode'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_id'), 'inventory_equipment', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_is_archived'), 'inventory_equipment', ['is_archived'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_reference'), 'inventory_equipment', ['reference'], unique=True)
    op.create_index(op.f('ix_inventory_equipment_serial_number'), 'inventory_equipment', ['serial_number'], unique=False)
    op.create_table('inventory_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False, comment='Firebase Storage URL'),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_name', sa.String(length=255), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['inventory_equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_version_id'], ['inventory_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_documents_equipment_id'), 'inventory_documents', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_inventory_documents_id'), 'inventory_documents', ['id'], unique=False)
    op.create_table('inventory_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('performer_type', sa.String(length=20), nullable=True),
    sa.Column('performer_user_id', sa.Integer(), nullable=True),
    sa.Column('performer_user_name', sa.String(length=255), nullable=True),
    sa.Column('performer_company', sa.String(length=255), nullable=True),
    sa.Column('performer_contact', sa.String(length=255), nullable=True),
    sa.Column('cost_labor', sa.Float(), nullable=True),
    sa.Column('cost_parts', sa.Float(), nullable=True),
    sa.Column('cost_other', sa.Float(), nullable=True),
    sa.Column('cost_total', sa.Float(), nullable=True),
    sa.Column('cost_currency', sa.String(length=10), nullable=True),
    sa.Column('parts_used_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['inventory_equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_maintenance_id'), 'inventory_maintenance', ['id'], unique=False)
    op.create_index('ix_maintenance_equipment_scheduled', 'inventory_maintenance', ['equipment_id', 'scheduled_date'], unique=False)
    op.create_index('ix_maintenance_status', 'inventory_maintenance', ['status'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('movement_type_id', sa.Integer(), nullable=False),
    sa.Column('movement_category', sa.String(length=50), nullable=False, comment='Categorie fonctionnelle: assignment, return, loan, transfer_site, etc.'),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('mission_title', sa.String(length=255), nullable=True),
    sa.Column('mission_type', sa.String(length=50), nullable=True),
    sa.Column('from_company_id', sa.Integer(), nullable=True),
    sa.Column('from_site_id', sa.Integer(), nullable=True),
    sa.Column('from_room_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('from_user_name', sa.String(length=255), nullable=True),
    sa.Column('from_specific_location', sa.String(length=255), nullable=True),
    sa.Column('to_company_id', sa.Integer(), nullable=True),
    sa.Column('to_site_id', sa.Integer(), nullable=True),
    sa.Column('to_room_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_name', sa.String(length=255), nullable=True),
    sa.Column('to_specific_location', sa.String(length=255), nullable=True),
    sa.Column('to_external_location', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, approved, rejected, completed'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_by_name', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('return_condition_json', sa.JSON(), nullable=True, comment='Etat au retour: conditionId, conditionName, notes, issues, photosUrls'),
    sa.Column('attachments_json', sa.JSON(), nullable=True, comment='Pieces jointes: [{name, url, type}]'),
    sa.Column('signature_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['inventory_equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_company_id'], ['inventory_companies.id'], ),
    sa.ForeignKeyConstraint(['from_room_id'], ['inventory_rooms.id'], ),
    sa.ForeignKeyConstraint(['from_site_id'], ['inventory_sites.id'], ),
    sa.ForeignKeyConstraint(['movement_type_id'], ['inventory_config_options.id'], ),
    sa.ForeignKeyConstraint(['to_company_id'], ['inventory_companies.id'], ),
    sa.ForeignKeyConstraint(['to_room_id'], ['inventory_rooms.id'], ),
    sa.ForeignKeyConstraint(['to_site_id'], ['inventory_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index('ix_movement_equipment_date', 'inventory_movements', ['equipment_id', 'date'], unique=False)
    op.create_index('ix_movement_status', 'inventory_movements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movement_status', table_name='inventory_movements')
    op.drop_index('ix_movement_equipment_date', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_maintenance_status', table_name='inventory_maintenance')
    op.drop_index('ix_maintenance_equipment_scheduled', table_name='inventory_maintenance')
    op.drop_index(op.f('ix_inventory_maintenance_id'), table_name='inventory_maintenance')
    op.drop_table('inventory_maintenance')
    op.drop_index(op.f('ix_inventory_documents_id'), table_name='inventory_documents')
    op.drop_index(op.f('ix_inventory_documents_equipment_id'), table_name='inventory_documents')
    op.drop_table('inventory_documents')
    op.drop_index(op.f('ix_inventory_equipment_serial_number'), table_name='inventory_equipment')
    op.drop_index(op.f('ix_inventory_equipment_reference'), table_name='inventory_equipment')
    op.drop_index(op.f('ix_inventory_equipment_is_archived'), table_name='inventory_equipment')
    op.drop_index(op.f('ix_inventory_equipment_id'), table_name='inventory_equipment')
    op.drop_index(op.f('ix_inventory_equipment_barcode'), table_name='inventory_equipment')
    op.drop_index('ix_equipment_is_archived', table_name='inventory_equipment')
    op.drop_index('ix_equipment_company_status', table_name='inventory_equipment')
    op.drop_index('ix_equipment_category', table_name='inventory_equipment')
    op.drop_table('inventory_equipment')
    op.drop_index(op.f('ix_inventory_rooms_id'), table_name='inventory_rooms')
    op.drop_table('inventory_rooms')
    op.drop_index('ix_subscription_status', table_name='inventory_subscriptions')
    op.drop_index('ix_subscription_is_archived', table_name='inventory_subscriptions')
    op.drop_index('ix_subscription_end_date', table_name='inventory_subscriptions')
    op.drop_index('ix_subscription_company', table_name='inventory_subscriptions')
    op.drop_index(op.f('ix_inventory_subscriptions_is_archived'), table_name='inventory_subscriptions')
    op.drop_index(op.f('ix_inventory_subscriptions_id'), table_name='inventory_subscriptions')
    op.drop_table('inventory_subscriptions')
    op.drop_index(op.f('ix_inventory_sites_id'), table_name='inventory_sites')
    op.drop_table('inventory_sites')
    op.drop_table('inventory_global_settings')
    op.drop_index(op.f('ix_inventory_config_options_list_type'), table_name='inventory_config_options')
    op.drop_index(op.f('ix_inventory_config_options_id'), table_name='inventory_config_options')
    op.drop_index('ix_config_option_type_active', table_name='inventory_config_options')
    op.drop_table('inventory_config_options')
    op.drop_index(op.f('ix_inventory_companies_id'), table_name='inventory_companies')
    op.drop_table('inventory_companies')
    # ### end Alembic commands ###
