"""ajout permissions inventory_subscriptions pour services

Revision ID: a5751a21438c
Revises: bde844f50f65
Create Date: 2026-02-24 12:48:32.887439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5751a21438c'
down_revision: Union[str, None] = 'bde844f50f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('inventory_subscriptions_view', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_subscriptions_create', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_subscriptions_edit', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_subscriptions_delete', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_subscriptions_manage', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'inventory_subscriptions_manage')
    op.drop_column('user_permissions', 'inventory_subscriptions_delete')
    op.drop_column('user_permissions', 'inventory_subscriptions_edit')
    op.drop_column('user_permissions', 'inventory_subscriptions_create')
    op.drop_column('user_permissions', 'inventory_subscriptions_view')
    # ### end Alembic commands ###
