"""add social permissions to user_permissions

Revision ID: a9d4371840fb
Revises: 469480ecb7fb
Create Date: 2026-02-26 16:07:21.857082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d4371840fb'
down_revision: Union[str, None] = '469480ecb7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('social_access_section', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_view_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_create_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_edit_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_delete_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_publish_posts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_view_inbox', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_reply_comments', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_delete_comments', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_reply_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_view_stats', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_export_stats', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_manage_accounts', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('social_manage_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'social_manage_settings')
    op.drop_column('user_permissions', 'social_manage_accounts')
    op.drop_column('user_permissions', 'social_export_stats')
    op.drop_column('user_permissions', 'social_view_stats')
    op.drop_column('user_permissions', 'social_reply_messages')
    op.drop_column('user_permissions', 'social_delete_comments')
    op.drop_column('user_permissions', 'social_reply_comments')
    op.drop_column('user_permissions', 'social_view_inbox')
    op.drop_column('user_permissions', 'social_publish_posts')
    op.drop_column('user_permissions', 'social_delete_posts')
    op.drop_column('user_permissions', 'social_edit_posts')
    op.drop_column('user_permissions', 'social_create_posts')
    op.drop_column('user_permissions', 'social_view_posts')
    op.drop_column('user_permissions', 'social_access_section')
    # ### end Alembic commands ###
