"""add scaleway permissions columns

Revision ID: b05f03948180
Revises: ba64d8353863
Create Date: 2026-02-25 22:48:53.289016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05f03948180'
down_revision: Union[str, None] = 'ba64d8353863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('scw_access_section', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('scw_view_instances', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('scw_view_dashboard', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('scw_view_billing', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('scw_view_domains', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('scw_view_account', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_permissions', sa.Column('scw_manage', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'scw_manage')
    op.drop_column('user_permissions', 'scw_view_account')
    op.drop_column('user_permissions', 'scw_view_domains')
    op.drop_column('user_permissions', 'scw_view_billing')
    op.drop_column('user_permissions', 'scw_view_dashboard')
    op.drop_column('user_permissions', 'scw_view_instances')
    op.drop_column('user_permissions', 'scw_access_section')
    # ### end Alembic commands ###
