"""add hierarchy_level to roles

Revision ID: bde844f50f65
Revises: d9fad7b8b954
Create Date: 2026-02-17 22:48:47.987916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bde844f50f65'
down_revision: Union[str, None] = 'd9fad7b8b954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('password_reset_tokens_token_key', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.add_column('roles', sa.Column('hierarchy_level', sa.Integer(), nullable=False, server_default='20'))
    op.drop_constraint('show_presenters_show_id_fkey', 'show_presenters', type_='foreignkey')
    op.create_foreign_key(None, 'show_presenters', 'shows', ['show_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show_presenters', type_='foreignkey')
    op.create_foreign_key('show_presenters_show_id_fkey', 'show_presenters', 'shows', ['show_id'], ['id'])
    op.drop_column('roles', 'hierarchy_level')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.create_unique_constraint('password_reset_tokens_token_key', 'password_reset_tokens', ['token'])
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invite_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
