"""add_capacity_kg_value_to_vehicles

Revision ID: bf0da3365124
Revises: 5a3a4cdd1142
Create Date: 2026-04-29 17:18:29.980758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0da3365124'
down_revision: Union[str, None] = '5a3a4cdd1142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistics_vehicles', sa.Column('capacity_kg_value', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistics_vehicles', 'capacity_kg_value')
    # ### end Alembic commands ###
