from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'bfdc86d253c7'
down_revision: Union[str, None] = '38dddbddd7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Ajouter les colonnes avec une valeur par défaut 'false' pour éviter les NULL
    op.add_column('user_permissions', sa.Column('can_acces_showplan_broadcast_section', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_acces_showplan_section', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_archiveStatusChange_showplan', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_changestatus_owned_showplan', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_changestatus_archived_showplan', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_setOnline_showplan', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_viewAll_showplan', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_acces_users_section', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_users', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_edit_users', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_desable_users', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_delete_users', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_manage_roles', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_assign_roles', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_acces_guests_section', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_guests', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_edit_guests', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_delete_guests', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_acces_presenters_section', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_presenters', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_edit_presenters', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_delete_presenters', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_acces_emissions_section', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_emissions', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_create_emissions', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_edit_emissions', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_delete_emissions', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_manage_emissions', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_notifications', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_manage_notifications', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_audit_logs', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_login_history', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_manage_settings', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_messages', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_send_messages', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_delete_messages', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_view_files', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_upload_files', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user_permissions', sa.Column('can_delete_files', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('user_permissions', 'can_delete_files')
    op.drop_column('user_permissions', 'can_upload_files')
    op.drop_column('user_permissions', 'can_view_files')
    op.drop_column('user_permissions', 'can_delete_messages')
    op.drop_column('user_permissions', 'can_send_messages')
    op.drop_column('user_permissions', 'can_view_messages')
    op.drop_column('user_permissions', 'can_manage_settings')
    op.drop_column('user_permissions', 'can_view_login_history')
    op.drop_column('user_permissions', 'can_view_audit_logs')
    op.drop_column('user_permissions', 'can_manage_notifications')
    op.drop_column('user_permissions', 'can_view_notifications')
    op.drop_column('user_permissions', 'can_manage_emissions')
    op.drop_column('user_permissions', 'can_delete_emissions')
    op.drop_column('user_permissions', 'can_edit_emissions')
    op.drop_column('user_permissions', 'can_create_emissions')
    op.drop_column('user_permissions', 'can_view_emissions')
    op.drop_column('user_permissions', 'can_acces_emissions_section')
    op.drop_column('user_permissions', 'can_delete_presenters')
    op.drop_column('user_permissions', 'can_edit_presenters')
    op.drop_column('user_permissions', 'can_view_presenters')
    op.drop_column('user_permissions', 'can_acces_presenters_section')
    op.drop_column('user_permissions', 'can_delete_guests')
    op.drop_column('user_permissions', 'can_edit_guests')
    op.drop_column('user_permissions', 'can_view_guests')
    op.drop_column('user_permissions', 'can_acces_guests_section')
    op.drop_column('user_permissions', 'can_assign_roles')
    op.drop_column('user_permissions', 'can_manage_roles')
    op.drop_column('user_permissions', 'can_delete_users')
    op.drop_column('user_permissions', 'can_desable_users')
    op.drop_column('user_permissions', 'can_edit_users')
    op.drop_column('user_permissions', 'can_view_users')
    op.drop_column('user_permissions', 'can_acces_users_section')
    op.drop_column('user_permissions', 'can_viewAll_showplan')
    op.drop_column('user_permissions', 'can_setOnline_showplan')
    op.drop_column('user_permissions', 'can_changestatus_archived_showplan')
    op.drop_column('user_permissions', 'can_changestatus_owned_showplan')
    op.drop_column('user_permissions', 'can_archiveStatusChange_showplan')
    op.drop_column('user_permissions', 'can_acces_showplan_section')
    op.drop_column('user_permissions', 'can_acces_showplan_broadcast_section')
    # ### end Alembic commands ###