"""create invite_tokens table

Revision ID: c2a6f1769b7f
Revises: b314bb576ceb
Create Date: 2025-05-02 22:04:59.080952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a6f1769b7f'
down_revision: Union[str, None] = 'b314bb576ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invite_tokens',
        sa.Column('token', sa.String(), primary_key=True, index=True),
        sa.Column('email', sa.String(), nullable=False, index=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_tokens')
    # ### end Alembic commands ###
