"""update presenter and segment

Revision ID: c37e5546990c
Revises: 12c471808d16
Create Date: 2024-12-27 17:08:09.066292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37e5546990c'
down_revision: Union[str, None] = '12c471808d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
      # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presenters', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('presenters', sa.Column('profilePicture', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presenters', sa.Column('isMainPresenter', sa.Boolean(), nullable=True))
    op.add_column('segments', sa.Column('startTime', sa.Text(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presenters', 'profilePicture')
    op.drop_column('presenters', 'biography')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('segments', 'startTime')
    op.drop_column('presenters', 'isMainPresenter')
    # ### end Alembic commands ###
