"""add public_alerts and listen_events tables

Revision ID: cd4d31b1077d
Revises: cd42bf43298f
Create Date: 2026-03-02 20:08:59.814021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4d31b1077d'
down_revision: Union[str, None] = 'cd42bf43298f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table('listen_events') and inspector.has_table('public_alerts'):
        return

    if not inspector.has_table('listen_events'):
        op.create_table('listen_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=100), nullable=False),
        sa.Column('event_type', sa.String(length=20), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('referrer', sa.String(length=500), nullable=True),
        sa.Column('page_url', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_listen_events_created_at'), 'listen_events', ['created_at'], unique=False)
        op.create_index('ix_listen_events_session_created', 'listen_events', ['session_id', 'created_at'], unique=False)
        op.create_index(op.f('ix_listen_events_session_id'), 'listen_events', ['session_id'], unique=False)
        op.create_index('ix_listen_events_type_created', 'listen_events', ['event_type', 'created_at'], unique=False)

    if not inspector.has_table('public_alerts'):
        op.create_table('public_alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('alert_type', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('starts_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_alerts')
    op.drop_index('ix_listen_events_type_created', table_name='listen_events')
    op.drop_index(op.f('ix_listen_events_session_id'), table_name='listen_events')
    op.drop_index('ix_listen_events_session_created', table_name='listen_events')
    op.drop_index(op.f('ix_listen_events_created_at'), table_name='listen_events')
    op.drop_table('listen_events')
    # ### end Alembic commands ###
