"""add max_articles to rss_feeds

Revision ID: d8385e6d3135
Revises: 6c44e9b35afd
Create Date: 2026-03-27 12:13:46.535030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8385e6d3135'
down_revision: Union[str, None] = '6c44e9b35afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_feeds', sa.Column('max_articles', sa.Integer(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_feeds', 'max_articles')
    # ### end Alembic commands ###
