"""Ajout des permissions inventory_* pour Inventaire

Revision ID: d9fad7b8b954
Revises: 75574b1232db
Create Date: 2026-02-05 15:19:01.348451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9fad7b8b954'
down_revision: Union[str, None] = '75574b1232db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('inventory_view', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_view_all_companies', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_view_values', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_create', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_edit', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_delete', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_move', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_approve_transfers', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_approve_company_loans', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_maintenance_create', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_maintenance_manage', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_manage_documents', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_manage_settings', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_permissions', sa.Column('inventory_manage_locations', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_permissions', 'inventory_manage_locations')
    op.drop_column('user_permissions', 'inventory_manage_settings')
    op.drop_column('user_permissions', 'inventory_manage_documents')
    op.drop_column('user_permissions', 'inventory_maintenance_manage')
    op.drop_column('user_permissions', 'inventory_maintenance_create')
    op.drop_column('user_permissions', 'inventory_approve_company_loans')
    op.drop_column('user_permissions', 'inventory_approve_transfers')
    op.drop_column('user_permissions', 'inventory_move')
    op.drop_column('user_permissions', 'inventory_delete')
    op.drop_column('user_permissions', 'inventory_edit')
    op.drop_column('user_permissions', 'inventory_create')
    op.drop_column('user_permissions', 'inventory_view_values')
    op.drop_column('user_permissions', 'inventory_view_all_companies')
    op.drop_column('user_permissions', 'inventory_view')

 
    # ### end Alembic commands ###
