"""add_breakdown_types_json_to_fiches_pannes

Revision ID: f94a7c7b88c4
Revises: 5d4f5469c74d
Create Date: 2026-04-28 13:07:45.519212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94a7c7b88c4'
down_revision: Union[str, None] = '5d4f5469c74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiches_pannes', sa.Column('breakdown_types_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiches_pannes', 'breakdown_types_json')
    # ### end Alembic commands ###
