name: construction du code d'automatisation de déploiement sur github et le serveur de production

on:
  - push
  - pull_request

jobs:
  Test-process:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git rep
        uses: actions/checkout@v2
      - name: say hi to happi
        run: echo "bonjour willy"
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installe all dependencies
        run: pip install -r requirements.txt
      

  processus_de_Deployement:
    runs-on: ubuntu-latest
    needs:
         - Test-process
    environment:
      nsme: production

    steps:
       - name: pulling git rep
         uses: actions/checkout@v2
       - name: deployement sur serveur ubuntu
         uses: appleboy/ssh-action@master
         with:
            host: ${{secrets.PROD_AUDACE_HOST}}
            username: ${{secrets.PROD_AUDACE_USERNAME}}
            password: ${{secrets.PROD_AUDACE_PASSWORD}}
            script: |
              cd app/src
              git pull
              sudo systemctrl restart api





          
       
        
