name: construction du code d'automatisation de déploiement sur github et le serveur de production

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git rep
        uses: actions/checkout@v2
      - name: say hi to happi
        run: echo "bonjour willy"
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: installe all dependencies
        run: pip install -r requirements.txt


          
       
        
