name: Construction du code d'automatisation de déploiement sur GitHub et le serveur de production

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test-process:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git Repository
        uses: actions/checkout@v2

      - name: Say Hi to Happi
        run: echo "Bonjour Willy"

      - name: Install Python Version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install All Dependencies
        run: pip install -r requirements.txt

      # Run unit tests
      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -q

  processus_de_deploiement:
    runs-on: ubuntu-latest
    needs:
      - Test-process
    environment:
      name: production

    steps:
      - name: Pull Git Repository
        uses: actions/checkout@v2

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_AUDACE_HOST }}
          username: ${{ secrets.PROD_AUDACE_USERNAME }}
          password: ${{ secrets.PROD_AUDACE_PASSWORD }}
          script: |
            cd app/src
            git checkout -- api_logs.log 
            git pull
            cd ..
            source venv/bin/activate
            cd src
            alembic upgrade head
            sudo systemctl restart api

      # - name: Check API Status
      #   run: curl -f http://${{ secrets.PROD_AUDACE_HOST }}/health || exit 1
      # git checkout -- api_logs.log   # Pour annuler les modifications sur le fichier api_logs.log
      # git pull # Pour récupérer les modifications sur le dépôt distant
      # alembic upgrade head # Pour mettre à jour la base de données
      # sudo systemctl restart api # Pour redémarrer le service API
